# Generated by Django 4.1 on 2022-08-12 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_role_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
